apiVersion: v1
kind: Secret
metadata:
  name: void-secrets
type: Opaque
stringData:
  VOID_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  VOID_POSTGRES_DSN: {{ .Values.secrets.postgresDSN | quote }}
  VOID_REDIS_ADDR: {{ .Values.secrets.redisAddr | quote }}
  VOID_NATS_URL: {{ .Values.secrets.natsURL | quote }}
