apiVersion: v1
kind: Service
metadata:
  name: void-api
spec:
  selector: { app: void-api }
  ports:
    - port: 80
      targetPort: {{ .Values.api.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: void-dashboard
spec:
  selector: { app: void-dashboard }
  ports:
    - port: 80
      targetPort: {{ .Values.dashboard.port }}
